personal_portfolio/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.blogs, name='blogs'),
    path("<int:blog_id>/", views.detail, name='detail')
]

personal_portfolio/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from skills import views as skills_views
from crafts import views as crafts_views
from todo import views as todo_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', skills_views.index, name='skills_index'),
    path('blog/', include('blog.urls')),
    path('crafts/', crafts_views.index, name='crafts_index'),
    path('crafts/create/', crafts_views.create, name='create_craft'),
    # Auth
    path('signup/', todo_views.signupuser, name='signupuser'),
    path('logout/', todo_views.logoutuser, name='logoutuser'),
    path('login/', todo_views.loginuser, name='loginuser'),
    # Todos

    # path('home/', todo_views.home, name='home'),
    # path('create', todo_views.createtodo, name='createtodo'),
    # path('current/', todo_views.currenttodos, name='currenttodos'),
    # Авторизация, Аутентификация, Задачи Приложения todo
    path('todo/', include('todo.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_portfolio/blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

personal_portfolio/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def blogs(request):
    blog = Blog.objects.order_by("-date")
    return render(request, 'blog/blogs.html', {'blogs': blog})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/details.html', {'blog': blog})

personal_portfolio/blog/templates/blog/blogs.html
{% extends 'skills/base.html' %}

{% block content %}

<h1>Блог</h1>

<h2 class="count">Постов: {{ blogs.count }}</h2>

{% for blog in blogs %}
<div class="element">
    <h2 class="top"><a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a></h2>
    <div class="blog_text">
        <h5>{{ blog.date|date:'d.m.Y' }}</h5>
        <p>{{ blog.description|striptags|truncatechars:360 }}</p>
    </div>
</div>
{% endfor %}
{% endblock %}

personal_portfolio/blog/templates/blog/details.html
{% extends 'skills/base.html' %}

{% block content %}

<div class="detail">
    <h1>{{ blog.title }}</h1>
    <h2>--{{ blog.date|date:'j E Y' }}--</h2>
    {{ blog.description|safe }}
</div>

{% endblock %}