personal_portfolio/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.blogs, name='blogs'),
    path("<int:blog_id>/", views.detail, name='detail')
]

personal_portfolio/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from skills import views as skills_views
from crafts import views as crafts_views
from todo import views as todo_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', skills_views.index, name='skills_index'),
    path('blog/', include('blog.urls')),
    path('crafts/', crafts_views.index, name='crafts_index'),
    path('crafts/create/', crafts_views.create, name='create_craft'),
    # Auth
    path('signup/', todo_views.signupuser, name='signupuser'),
    path('logout/', todo_views.logoutuser, name='logoutuser'),
    path('login/', todo_views.loginuser, name='loginuser'),
    # Todos

    # path('home/', todo_views.home, name='home'),
    # path('create', todo_views.createtodo, name='createtodo'),
    # path('current/', todo_views.currenttodos, name='currenttodos'),
    # Авторизация, Аутентификация, Задачи Приложения todo
    path('todo/', include('todo.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_portfolio/todo/urls.py
from django.urls import path
from . import views
from todo import views as todo_views
from skills import views as skills_views
from crafts import views as crafts_views


app_name = 'todo'

urlpatterns = [
    path('skills/', skills_views.index, name='skills_index'),
    path('crafts/', crafts_views.index, name='crafts_index'),
    # Auth
    # path("signup/", views.signupuser, name='signupuser'),
    # Auth
    path('signup/', todo_views.signupuser, name='signupuser'),
    path('logout/', todo_views.logoutuser, name='logoutuser'),
    path('login/', todo_views.loginuser, name='loginuser'),
# Todos
    path('home/', todo_views.home, name='home'),
    path('create', todo_views.createtodo, name='createtodo'),
    path('current/', todo_views.currenttodos, name='currenttodos'),
    path('todo/<int:todo_pk>', todo_views.viewtodo, name='viewtodo'),
    path('todo/<int:todo_pk>/complete', todo_views.completetodo, name='completetodo'),
    path('todo/<int:todo_pk>/delete', todo_views.deletetodo, name='deletetodo'),
    path('completed/', todo_views.completedtodo, name='completedtodo'),
    # Todos
    # path('current/', views.currenttodos, name='currenttodos'),
]

personal_portfolio/todo/models.py
from django.db import models
from django.contrib.auth.models import User


class Todo(models.Model):
    title = models.CharField(max_length=100)
    memo = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    date_completed = models.DateTimeField(null=True, blank=True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

personal_portfolio/todo/forms.py
# from django.forms import EmailField
#
# from django.utils.translation import ugettext_lazy as _
#
# from django.contrib.auth.models import User
# from django.contrib.auth.forms import UserCreationForm
#
#
# class UserCreationForm(UserCreationForm):
#     email = EmailField(label=_("Email address"), required=True,
#         help_text=_("Required."))
#
#     class Meta:
#         model = User
#         fields = ("username", "email", "password1", "password2")
#
#     def save(self, commit=True):
#         user = super(UserCreationForm, self).save(commit=False)
#         user.email = self.cleaned_data["email"]
#         if commit:
#             user.save()
#         return user

# from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# from django import forms
# from django.contrib.auth.models import User


# class CustomAuthFormUser(AuthenticationForm):
#     class Meta:
#         model = User
#         fields = ['username', 'email', 'password']

# class CustomAuthenticationForm(AuthenticationForm):
#     email = forms.EmailField(widget=forms.TextInput(attrs={'autofocus': True}))

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from .models import Todo


class CustomUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'memo', 'important']

personal_portfolio/todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from crafts import models as models_crafts
from skills import models as models_skills
from .forms import CustomUserForm, TodoForm
# from .forms import CustomAuthFormUser
from .models import Todo


def index(request):
    projects = models_skills.Skills.objects.all()
    return render(request, 'todo:skills_index.html', {'projects': projects})

def index(request):
    projects = models_crafts.objects.all()
    return render(request, 'todo:crafts_index.html', {'projects': projects})



def home(request):
    return render(request, 'todo/home.html')


def signupuser(request):
    if request.method == 'GET':
        return render(request, 'todo/signupuser.html', {'form': CustomUserForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(username=request.POST['username'], email=request.POST['email'],
                                                password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('crafts_index')
            except IntegrityError:
                return render(request, 'todo/signupuser.html', {'form': CustomUserForm(),
                                        'error': 'Такое имя'
                                        'Пользователя уже'
                                        'существует.'
                                        'Задайте другое.'})
        else:
            return render(request, 'todo/signupuser.html', {'form': CustomUserForm(),
                                                            'error': 'Пароли Не Совпадают.'})


def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('todo:home')


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'todo/loginuser.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'],
                            # email=request.POST['email'],
                            password=request.POST['password'])
        if user is None:
            return render(request, 'todo/loginuser.html', {'form': AuthenticationForm(),
                                                           'error': 'Неверные данные '})
        else:
            login(request, user)
            return redirect('todo:currenttodos')


@login_required
def currenttodos(request):
    todos = Todo.objects.filter(user=request.user, date_completed__isnull=True)
    return render(request, 'todo/currenttodos.html', {'todos': todos})


@login_required
def createtodo(request):
    if request.method == 'GET':
        return render(request, 'todo/createtodo.html', {'form': TodoForm()})
    else:
        try:
            form = TodoForm(request.POST)
            new_todo = form.save(commit=False)
            new_todo.user = request.user
            new_todo.save()
            return redirect('todo:currenttodos')
        except ValueError:
            return render(request, 'todo/createtodo.html', )


@login_required
def viewtodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk)
    if request.method == 'GET':
        form = TodoForm(instance=todo)
        return render(request, 'todo/viewtodo.html', {'todo': todo, 'form': form})
    else:
        try:
            form = TodoForm(request.POST, instance=todo)
            form.save()
            return redirect('todo:currenttodos')
        except ValueError:
            return render(request, 'todo/viewtodo.html', {'todo': todo, 'form': form,
                                                         'error': 'Неверные данные.'})


@login_required
def completetodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == 'POST':
        todo.date_completed = timezone.now()
        todo.save()
        return redirect('todo:currenttodos')

@login_required
def deletetodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == 'POST':
        todo.delete()
        return redirect('todo:currenttodos')


@login_required
def completedtodo(request):
    todos = Todo.objects.filter(user=request.user,
                                date_completed__isnull=False).order_by('-date_completed')
    return render(request, 'todo/completedtodo.html', {'todos': todos})

personal_portfolio/todo/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
</head>
<body>
    <div class="menu">
        <div class="wrap">
            <div class="logo">
                <a href="{% url 'skills_index' %}"><img src="{% static 'skills/logo.png' %}" alt=""></a>
                <a href="{% url 'crafts_index' %}"><img src="{% static 'skills/self_make2.jpg' %}" style="width:50px; height:50px;" alt=""></a>
            </div>
        </div>
    </div>
{% if user.is_authenticated %}

<div class="menu">
    <div class="wrap">
        
        <ul>
            <li class="logo">Пользователь: {{ user.username }}</li>
            <li><a href="{% url 'todo:createtodo' %}">Создать</a></li>
            <li><a href="{% url 'todo:currenttodos' %}">Актуальные</a></li>
            <li><a href="{% url 'todo:completedtodo' %}">Выполненные</a></li>
            <li>
                <form action="{% url 'todo:logoutuser' %}" method="post">
                    {% csrf_token %}
                    <button class="top">Выйти</button>
                </form>
            </li>
        </ul>
    </div>
</div>
{% else %}
<div class="menu">
    <div class="wrap">
        <ul>
            <li class="logo"><a href="{% url 'todo:home' %}">Модуль Todo</a></li>
            <li><a href="{% url 'todo:signupuser' %}">Зарегистрироваться</a></li>
            <li><a href="{% url 'todo:loginuser' %}">Войти</a></li>
        </ul>
    </div>
</div>
{% endif %}
<div class="content">
    <div class="wrap">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

personal_portfolio/todo/templates/todo/completedtodo.html
{% extends 'todo/base.html' %}
{% block content %}
<h1>Завершено::</h1>

<ul>
    {% for todo in todos %}
    <li>
        <a href="{% url 'todo:viewtodo' todo.id %}">
            {% if todo.important %}
            <b>{{ todo.title }}</b>
            {% else %}
            {{ todo.title }}
            {% endif %}
            {% if todo.memo %}
            - {{ todo.memo }}
            {% endif %}
            {{ todo.date_completed|date:'M j Y H:i'}}
        </a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

personal_portfolio/todo/templates/todo/createtodo.html
{% extends 'todo/base.html' %}

{% block content %}
<h1>Создание задачи</h1>
<h2>{{ error }}</h2>
<form method="post" class="bg">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="center">
        <button class="btn">Создать</button>
    </div>
</form>
{% endblock %}

personal_portfolio/todo/templates/todo/currenttodos.html
{% extends 'todo/base.html' %}
{% load static %}
{% block content %}
<h1>Задачи</h1>

<ul>
    {% for todo in todos %}
    <li>
        <a href="{% url 'todo:viewtodo' todo.id %}">
        {% if todo.important %}
            <b>{{ todo.title }}</b>
        {% else %}
            {{ todo.title }}
        {% endif %}

        {% if todo.memo %}
        - {{ todo.memo }}
        {% endif %}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

personal_portfolio/todo/templates/todo/home.html
{% extends 'todo/base.html' %}
{% load static %}
{% block content %}

<div class="center">
    <h1>Модуль Todo для Регистрации, Выполнения, Удаления Пользователей</h1>
    <h2>Этот Модуль Предназначен для обеспечения Регистрации
        Пользователей в Todo. <br>
        Skills, Blogs, Crafts - Могут видеть все пользователи </h2>
    <p>Помогает находить слабые стороны
        в работе сотрудника и Улучшить Их</p>

    <form action="{% url 'loginuser' %}" class="center">
        <button class="btn">Начать</button>
    </form>
</div>
{% endblock content %}

personal_portfolio/todo/templates/todo/loginuser.html
{% extends 'todo/base.html' %}

{% block content %}

<h1>Авторизация</h1>
<h2>{{ error }}</h2>
<form method="post" class="bg">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="center">
        <button class="btn">Авторизация</button>
    </div>
</form>

{% endblock content %}

personal_portfolio/todo/templates/todo/signupuser.html
{% extends 'todo/base.html' %}

{% block content %}
    <h1>Регистрация</h1>
    <form method="post" class="register">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn">Зарегистрироваться</button>
    </form>
{% endblock content %}

personal_portfolio/todo/templates/todo/viewtodo.html
{% extends 'todo/base.html' %}

{% block content %}
<h1>{{ todo.title }}</h1>
{{ error }}
<div class="but">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn">Сохранить</button>
    </form>

    <form action="{% url 'todo:completetodo' todo.id %}" method="post">
        {% csrf_token %}
        <button class="btn good">Выполненно</button>
    </form>

    <form action="{% url 'todo:deletetodo' todo.id %}" method="post">
        {% csrf_token %}
        <button class="btn remove">Удалить</button>
    </form>
</div>
{% endblock content %}