personal_portfolio/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.blogs, name='blogs'),
    path("<int:blog_id>/", views.detail, name='detail')
]

personal_portfolio/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from skills import views as skills_views
from crafts import views as crafts_views
from todo import views as todo_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', skills_views.index, name='skills_index'),
    path('blog/', include('blog.urls')),
    path('crafts/', crafts_views.index, name='crafts_index'),
    path('crafts/create/', crafts_views.create, name='create_craft'),
    # Auth
    path('signup/', todo_views.signupuser, name='signupuser'),
    path('logout/', todo_views.logoutuser, name='logoutuser'),
    path('login/', todo_views.loginuser, name='loginuser'),
    # Todos

    # path('home/', todo_views.home, name='home'),
    # path('create', todo_views.createtodo, name='createtodo'),
    # path('current/', todo_views.currenttodos, name='currenttodos'),
    # Авторизация, Аутентификация, Задачи Приложения todo
    path('todo/', include('todo.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_portfolio/todo/urls.py
from django.urls import path
from . import views
from todo import views as todo_views
from skills import views as skills_views
from crafts import views as crafts_views


app_name = 'todo'

urlpatterns = [
    path('skills/', skills_views.index, name='skills_index'),
    path('crafts/', crafts_views.index, name='crafts_index'),
    # Auth
    # path("signup/", views.signupuser, name='signupuser'),
    # Auth
    path('signup/', todo_views.signupuser, name='signupuser'),
    path('logout/', todo_views.logoutuser, name='logoutuser'),
    path('login/', todo_views.loginuser, name='loginuser'),
# Todos
    path('home/', todo_views.home, name='home'),
    path('create', todo_views.createtodo, name='createtodo'),
    path('current/', todo_views.currenttodos, name='currenttodos'),
    path('todo/<int:todo_pk>', todo_views.viewtodo, name='viewtodo'),
    path('todo/<int:todo_pk>/complete', todo_views.completetodo, name='completetodo'),
    path('todo/<int:todo_pk>/delete', todo_views.deletetodo, name='deletetodo'),
    path('completed/', todo_views.completedtodo, name='completedtodo'),
    # Todos
    # path('current/', views.currenttodos, name='currenttodos'),
]

personal_portfolio/skills/models.py
from django.db import models
from django.contrib.auth.models import User


class Skills(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='skills/images/')
    url = models.URLField(blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

personal_portfolio/skills/views.py
from django.shortcuts import render
from .models import Skills


def index(request):
    projects = Skills.objects.all()
    return render(request, 'skills/skills_index.html', {'projects': projects})

personal_portfolio/skills/templates/skills/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="icon" href="{% static 'skills/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <link href = "i:/PythonCours/Python/OlgaProject_Archive/font/stylesheet.css" rel = "stylesheet" type = "text/css"/>
</head>

<body>


        <div class="menu1">

        <div class="wrap1">
            <div class="logo">
                <a href="{% url 'crafts_index' %}"><img src="{% static 'skills/self_make2.jpg' %}" style="width:50px; height:50px;" alt=""></a>
                <a href="{% url 'skills_index' %}"><img src="{% static 'skills/logo.png' %}" alt=""></a>
            </div>
            <ul>
                <li><a href="{% url 'todo:home' %}">Модуль Todo</a></li>
            </ul>
            
            <ul>
                <li>
                    <a href="{% url 'skills_index' %}">Главная  </a>
                </li>
                <li>
                    <a href="{% url 'blog:blogs' %}">Блог  </a>
                </li>
                <li>
                    <a href="{% url 'crafts_index' %}">Делаем Своими Руками </a>
                </li>
                <li>
                    <a href="{% static 'skills/resumeBaskirovAAwithoutTel.pdf' %}" target="_blank">Резюме</a>
                </li>
            </ul>
        </div>

    </div>


  <div class="content">

    <div class="wrap">
      {% block content %}
      {% endblock content %}
    </div>

  </div>

</body>
</html>

personal_portfolio/skills/templates/skills/skills_index.html
{% extends 'skills/base.html' %}

{% block content %}

{% load static %}

<h1>Портфолио разработчика: </h1>

<div class="img">
    <img src="{% static 'skills/wc.jpg' %}" alt="">
</div>

<h2>Стек технологий: </h2>

<div class="block">
    {% for project in projects %}
    <div class="element">
        <div><img src="{{ project.image.url }}" alt=""></div>
        <div class="text">
            <h2><a href="{{ project.url }}" target="_blank">{{ project.title }}</a></h2>
            <p>{{ project.description }}</p>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}